# This file was generated by GoReleaser. DO NOT EDIT.
class GithubToy < Formula
  desc "Toy to operate github"
  homepage "https://github.com/yukihirop/github-toy"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yukihirop/github-toy/releases/download/v0.1.4/github-toy_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "a0457ba492990d22ee6f533697ebe1d2d07d26683ba5b2b44fd5e5cf89289b78"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yukihirop/github-toy/releases/download/v0.1.4/github-toy_0.1.4_Linux_x86_64.tar.gz"
      sha256 "3dcbd1ad1459b4cbfd7865d23356a35a960b54fb1133b8907d0894c3aa940f7f"
    end
  end
  
  depends_on "go"

  def install
    bin.install "gtoy"
  end

  test do
    system "#{bin}/gtoy"
  end
end
