# This file was generated by GoReleaser. DO NOT EDIT.
class GithubToy < Formula
  desc "Toy to operate github"
  homepage "https://github.com/yukihirop/github-toy"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yukihirop/github-toy/releases/download/v0.1.2/github-toy_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "d6504b4cf1213720db5603bc30b66a5cc5cebb423f1b941f27a92f87a7b8d738"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yukihirop/github-toy/releases/download/v0.1.2/github-toy_0.1.2_Linux_x86_64.tar.gz"
      sha256 "d70795b1a14202235a3526b15878afd0a804c7dc7ee6c56fdd196713aa56ea7c"
    end
  end
  
  depends_on "go"

  def install
    bin.install "github-toy"
  end

  test do
    system "#{bin}/gtoy"
  end
end
