# This file was generated by GoReleaser. DO NOT EDIT.
class Gtoy < Formula
  desc "Toy to operate github"
  homepage "https://github.com/yukihirop/github-toy"
  version "0.1.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yukihirop/github-toy/releases/download/v0.1.11/github-toy_0.1.11_Darwin_x86_64.tar.gz"
    sha256 "76f3d6a24612475c8a38cdee94e8b0122255e8c13187e3aaddf8f8d601af2e5f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yukihirop/github-toy/releases/download/v0.1.11/github-toy_0.1.11_Linux_x86_64.tar.gz"
      sha256 "0d4674bfebf29055eb8a344bfe922a30150de55cfcdd9d532b99ae40e56f1ca7"
    end
  end
  
  depends_on "go"

  def install
    bin.install "bin/gtoy"
  end

  test do
    system "#{bin}/gtoy"
  end
end
